### ISSUE TITLE
Change output filename 

### ISSUE THREAD

**Issue by nick-gibb** [nick-gibb/points_to_polys#1]
Hi Scott, 

Good that the script runs locally on your PC

I made a small change here, to give it a constant output filename (Scott from Infobase requested this)

https://github.com/nick-gibb/points_to_polys/commit/6a4959358f5539bc31cf263fd4fdffbcfe17d78d

Can you pull this latest code and re-generate the output file? 

And then we will need to upload it to the appropriate Blob container, and maybe also notify Scott's team by email. I'll make a separate issue for that. 

Thanks

**Comment by srt749** [comment]
Resolved - output file confirmed to have intended file name
