### ISSUE TITLE
Auto-upload the output file to Blob storage

### ISSUE THREAD

**Issue by nick-gibb** [nick-gibb/points_to_polys#3]
Hey Scott T.,

The script is currently generating a csv file locally. We want to upload this to Blob storage container automatically. 

There is a Python library for connecting to Azure Blob Storage. You need a SAS token as well. I will send you the Blob Container details where the file should go. 

Really important: SAS keys should not be hard-coded and version controlled (it's like a password). They can be a command-line argument.

**Comment by nick-gibb** [comment]
Hey Scott, so over Teams you see where the file will go (i.e. which container in Blob Storage). 

If you could try to alter the code to upload there that'd be good.

You'll need this library
https://github.com/Azure/azure-storage-python

maybe this is useful
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python

You'll also need a SAS token, I will email that to you

**Comment by srt749** [comment]
Got this working, tested with last week's output file which is now in the fluwatchers blob. I made a branch "srt" with code (in map_fsa_hr.py) that will upload the output file to a container named "fluwatchers", to a storage account identified by a key the user provides. The user has to provide the Connection String in the same way as the other cmd arguments, like: -k "connection string".
