### ISSUE TITLE
Replace "Canada" with 1 in HRUID column

### ISSUE THREAD

**Issue by nick-gibb** [nick-gibb/points_to_polys#4]
At the request of Infobase

**Comment by srt749** [comment]
Tested this change, pushing to the branch 'srt' in case you would like to review any changes 

Old code:    
df_canada = pd.DataFrame([[canada_participants, canada_confirmed_positive]], columns=list(['participants', 'confirmed_positive']), index=['Canada'])

New code:    
df_canada = pd.DataFrame([[canada_participants, canada_confirmed_positive]], columns=list(['participants', 'confirmed_positive']), index=['1'])
